"""remove ref_url

Revision ID: d4e0ab08cb45
Revises: b649c8755bd4
Create Date: 2025-10-23 13:02:31.474568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e0ab08cb45'
down_revision: Union[str, Sequence[str], None] = 'b649c8755bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ref_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ref_url', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
